version: "3.1"

services:

  db:
    restart: always
    image: postgres
    container_name: MO-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - MO_data:/var/lib/postgresql/data/
      - ./Resources/scripts/:/data/
    
  backend:
    depends_on:
      - db
    restart: always
    build:
      context: "./backend"
      dockerfile: Dockerfile
    container_name: MO-backend
    env_file: ".env"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code

volumes:
  MO_data:
